const router=require('express').Router();
const multer=require('multer');
const cloudinaryHelper=require('../../helpers/cloudinary.helper');
const upload=multer({storage:cloudinaryHelper.storage});
const tourController=require('../../controllers/admin/tour.controller');
router.get('/list',tourController.list);
router.get('/create',tourController.create);
router.post('/create',upload.single("avatar"),tourController.createPost);
router.get('/trash',tourController.trash);
module.exports=router;