const mongoose=require('mongoose');

const userSchema=new mongoose.Schema({
  fullName:{
    type:String,
    required:true,
    trim:true
  },
  email:{
    type:String,
    required:true,
    unique:true,
    lowercase:true,
    trim:true
  },
  password:{
    type:String,
    required:true,
    select:false
  },
  phone:{
    type:String,
    default:""
  },
  avatar:{
    type:String,
    default:""
  },
  preferences:{
    tourTypes:{
      type:[String],
      default:[]
    },
    budgetRange:{
      min:{type:Number,default:0},
      max:{type:Number,default:0}
    },
    locations:{
      type:[String],
      default:[]
    }
  },
  cart:[{
    tourId:{
      type:mongoose.Schema.Types.ObjectId,
      ref:"Tour",
      required:true
    },
    locationFrom:{
      type:mongoose.Schema.Types.ObjectId,
      ref:"City",
      required:true
    },
    quantityAdult:{
      type:Number,
      min:0,
      default:0
    },
    quantityChildren:{
      type:Number,
      min:0,
      default:0
    },
    quantityBaby:{
      type:Number,
      min:0,
      default:0
    },
    checked:{
      type:Boolean,
      default:true
    }
  }],
  status:{
    type:String,
    enum:["active","inactive"],
    default:"active"
  },
  deleted:{
    type:Boolean,
    default:false
  },
  deletedAt:Date,
  updatedBy:String,
  deletedBy:String
},{
  timestamps:true
});

module.exports=mongoose.model('User',userSchema,'users');
